name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows"
            os: windows-latest
          - name: "MacOS"
            os: macos-latest
          - name: "Ubuntu"
            os: ubuntu-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assemble --stacktrace
      - name: Run tests
        run: |
            set RUST_BACKTRACE=1
            ./gradlew test